In [1]:
import numpy as np


In [5]:
np.__version__

'1.26.4'

In [6]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [7]:
ls  = [25,10,20,30,40,50,60]
arr = np.array(ls)
arr

array([25, 10, 20, 30, 40, 50, 60])

In [8]:
type(arr)

numpy.ndarray

In [9]:
arr.ndim # cheching the dimension of array

1

In [11]:
arr.size # total item in your array


7

In [12]:
len(arr)

7

In [13]:
arr.dtype

dtype('int32')

In [14]:
arr = np.array([25,10,20,30,40,50,60,25.2])
arr

array([25. , 10. , 20. , 30. , 40. , 50. , 60. , 25.2])

In [15]:
arr.dtype

dtype('float64')

In [16]:
arr = np.array([25,10,20,30,40,50,60])
arr

array([25, 10, 20, 30, 40, 50, 60])

In [17]:
arr[2]

20

In [18]:
arr[3:]

array([30, 40, 50, 60])

In [19]:
arr[4:]

array([40, 50, 60])

In [20]:
arr[:-3]

array([25, 10, 20, 30])

In [21]:
arr[-3:]

array([40, 50, 60])

In [25]:
arr[-1:-4:-1]

array([60, 50, 40])

In [26]:
arr[-3:]

array([40, 50, 60])

In [27]:
arr+5 # increment in array +5


array([30, 15, 25, 35, 45, 55, 65])

In [28]:
max(arr)

60

In [29]:
min(arr)

10

In [30]:
sum(arr)

235

In [31]:
np.mean(arr)

33.57142857142857

In [33]:
np.median(arr)

30.0

In [39]:
arr = np.array([25,10,20,30,40,50,60,25,60])
arr

array([25, 10, 20, 30, 40, 50, 60, 25, 60])

In [42]:
mod(arr)

NameError: name 'mod' is not defined

In [36]:
np.random.randint(1,9) #1 to 9

5

In [38]:
arr = np.random.randint(1,450,500)  # array of 500 item in between 1 to 450
arr

array([402,   8,  49,  88, 158, 115,  93, 173, 444, 411, 368, 164,  65,
       157, 385, 423, 387,  92,  49, 236, 308, 239, 324, 416, 182, 230,
       366,  21,  60, 341, 245, 431, 374, 265,  97, 370, 408, 339, 296,
       411,  34,  56, 391,  61, 353,  34, 379, 209,  80,  88, 426, 216,
       304, 116, 445, 423, 376, 248, 136, 147,  78, 252, 278,  59, 284,
       441, 415, 167, 120, 218, 271, 212, 274, 390,  23, 149, 391, 346,
       368, 245, 289, 419, 389, 276,   3, 114, 271,  28, 442, 314, 377,
       396,  92, 207, 292,  15,  95, 303, 440, 108, 320, 179, 365, 161,
       428, 375, 200, 230,  53,  34, 285, 381, 171,  31, 230,  78, 144,
       315, 242, 398,  39,  40, 392,  24, 168, 412,  23, 128, 306, 322,
       222,  72, 418, 163, 406, 151, 112,   6,  25, 137, 364, 196, 160,
       196, 416, 195, 228, 125,  45, 116, 436, 427,  92, 302,  40, 199,
       393,  45, 251,  21, 286,  46, 265,  15, 231, 252, 397, 446, 267,
         7, 351,  36, 365,  85, 262, 264, 328, 352, 157, 146, 20

In [43]:
import random ,string

In [44]:
string.punctuation

'!"#$%&\'()*+,-./:;<=>?@[\\]^_`{|}~'

In [45]:
string.ascii_letters

'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ'

In [47]:
string.digits

'0123456789'